/**
 * Betfair: Exchange Streaming API
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cc.xuloo.betfair.client.stream;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Value;

import java.util.List;


/**
 * MarketDataFilter
 */
@Value
@Builder
public class MarketDataFilter   {

  /**
   * Gets or Sets fields
   */
  public enum FieldsEnum {

    EX_BEST_OFFERS_DISP("EX_BEST_OFFERS_DISP"),

    EX_BEST_OFFERS("EX_BEST_OFFERS"),

    EX_ALL_OFFERS("EX_ALL_OFFERS"),

    EX_TRADED("EX_TRADED"),

    EX_TRADED_VOL("EX_TRADED_VOL"),

    EX_LTP("EX_LTP"),

    EX_MARKET_DEF("EX_MARKET_DEF"),

    SP_TRADED("SP_TRADED"),

    SP_PROJECTED("SP_PROJECTED");

    private String value;

    FieldsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  private final Integer ladderLevels;

  private final List<FieldsEnum> fields;

    public MarketDataFilter(@JsonProperty("ladderLevels") Integer ladderLevels,
                            @JsonProperty("fields") List<FieldsEnum> fields) {
        this.ladderLevels = ladderLevels;
        this.fields = fields;
    }
}

