/**
 * Betfair: Exchange Streaming API
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cc.xuloo.betfair.client.stream;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Value;

import java.util.List;


/**
 * OrderMarketChange
 */
@Value
public class OrderMarketChange   {

  private final Long accountId;

  /**
   * Order Changes - a list of changes to orders on a selection
   * @return orc
   **/
  private final List<OrderRunnerChange> orc;

  private final Boolean closed;

  /**
   * Market Id - the id of the market the order is on
   * @return id
   **/
  private final String id;

  public OrderMarketChange(@JsonProperty("accountId") Long accountId,
                           @JsonProperty("orc") List<OrderRunnerChange> orc,
                           @JsonProperty("closed") Boolean closed,
                           @JsonProperty("id") String id) {
    this.accountId = accountId;
    this.orc = orc;
    this.closed = closed;
    this.id = id;
  }
}

